version: "3.8"

services:
  api:
    container_name: QS-SmartBand-API
    restart: on-failure
    build:
      context: .
      dockerfile: ./API/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ConnectionString=Server=db,1433;Database=API;User=sa;Password=f4KxZH1ltWJdpov
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443;
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Jv84vLfS6eSpBzi
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/dev-cert.pfx
    depends_on:
      - db
  db:
    container_name: QS-SmartBand-Database
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=f4KxZH1ltWJdpov
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - ./MSSQL-Data:/var/opt/mssql/data
